import React from 'react'

export const Home: React.FC = () => {
  return (
    <>
      <h1>Redux + TypeScript</h1>
      <p>
        Hello and welcome! :) This app was generated by the Create React App
      </p>
    </>
  )
}
